package com.alechilles.patchwork.engine;

import com.alechilles.patchwork.conditions.PatchCondition;
import com.alechilles.patchwork.conditions.PatchConditionParser;
import com.alechilles.patchwork.format.PatchFormat;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/** Parsed Patchwork definition associated with one target asset and source location. */
public final class PatchDefinition {
    /** Stable definition ordering: priority, patch ID, then contributing pack load order. */
    public static final Comparator<PatchDefinition> ORDERING=Comparator.comparingInt(PatchDefinition::priority).thenComparing(PatchDefinition::id).thenComparingInt(PatchDefinition::sourcePackLoadOrder);
    private final String id,target,sourcePack,sourcePath; private final int priority,sourcePackLoadOrder,formatVersion; private final boolean enabled; private final List<PatchOperation> operations; private final PatchCondition condition;
    private PatchDefinition(String id,String target,int priority,boolean enabled,List<PatchOperation> operations,String sourcePack,String sourcePath,int sourcePackLoadOrder,PatchCondition condition,int formatVersion){this.id=id;this.target=target;this.priority=priority;this.enabled=enabled;this.operations=List.copyOf(operations);this.sourcePack=sourcePack;this.sourcePath=sourcePath;this.sourcePackLoadOrder=sourcePackLoadOrder;this.condition=condition;this.formatVersion=formatVersion;}
    /** Parses one target definition, defaulting source pack order to zero. */ public static PatchDefinition parse(JsonObject root,String sourcePack,String sourcePath){return parse(root,sourcePack,sourcePath,0);}
    /** Parses one target definition with a deterministic source pack load order. */ public static PatchDefinition parse(JsonObject root,String sourcePack,String sourcePath,int sourcePackLoadOrder){List<PatchDefinition> definitions=parseAll(root,sourcePack,sourcePath,sourcePackLoadOrder);if(definitions.isEmpty())throw new IllegalArgumentException("Patch '"+sourcePack+":"+sourcePath+"' produced no definitions.");return definitions.getFirst();}
    /** Parses a definition for each declared target, defaulting source pack order to zero. */ public static List<PatchDefinition> parseAll(JsonObject root,String sourcePack,String sourcePath){return parseAll(root,sourcePack,sourcePath,0);}
    /** Parses a definition for each declared target with the supplied source pack load order. */ public static List<PatchDefinition> parseAll(JsonObject root,String sourcePack,String sourcePath,int sourcePackLoadOrder){PatchFormat format=PatchFormat.fromRoot(root);if(format.isVersion2())validateV2RootFields(root);String id=readString(root,"Id",sourcePack+":"+sourcePath);List<PatchOperation> operations=readOperations(root,id,format.version());validateSentinel(operations,id,format.version());PatchCondition condition=new PatchConditionParser().parseOptional(root);List<PatchDefinition> result=new ArrayList<>();for(String target:readTargets(root,id))result.add(new PatchDefinition(id,target,readInt(root,"Priority",0),readBoolean(root,"Enabled",true),operations,sourcePack,sourcePath,sourcePackLoadOrder,condition,format.version()));return result;}
    public String id(){return id;} public String target(){return target;} public int priority(){return priority;} public boolean enabled(){return enabled;} public List<PatchOperation> operations(){return operations;} public String sourcePack(){return sourcePack;} public String sourcePath(){return sourcePath;} public int sourcePackLoadOrder(){return sourcePackLoadOrder;} public PatchCondition condition(){return condition;} public int formatVersion(){return formatVersion;}
    public String getId(){return id();} public String getTarget(){return target();} public int getPriority(){return priority();} public boolean isEnabled(){return enabled();} public List<PatchOperation> getOperations(){return operations();} public String getSourcePack(){return sourcePack();} public String getSourcePath(){return sourcePath();} public int getSourcePackLoadOrder(){return sourcePackLoadOrder();} public int getFormatVersion(){return formatVersion();}
    static String readRequiredString(JsonObject object,String name,String context){String value=readString(object,name,null);if(value==null||value.isBlank())throw new IllegalArgumentException(context+" must define non-empty "+name+".");return value;}
    static String readString(JsonObject object,String name,String fallback){JsonElement value=object.get(name);if(value==null||value.isJsonNull())return fallback;if(!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isString())throw new IllegalArgumentException(name+" must be a string.");return value.getAsString();}
    static int readInt(JsonObject object,String name,int fallback){JsonElement value=object.get(name);if(value==null||value.isJsonNull())return fallback;if(!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isNumber())throw new IllegalArgumentException(name+" must be an integer.");try{return new BigDecimal(value.getAsString()).intValueExact();}catch(NumberFormatException|ArithmeticException failure){throw new IllegalArgumentException(name+" must be an integer.",failure);}}
    static boolean readBoolean(JsonObject object,String name,boolean fallback){JsonElement value=object.get(name);if(value==null||value.isJsonNull())return fallback;if(!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isBoolean())throw new IllegalArgumentException(name+" must be a boolean.");return value.getAsBoolean();}
    private static List<PatchOperation> readOperations(JsonObject root,String id,int formatVersion){JsonElement raw=root.get("Operations");if(raw==null||!raw.isJsonArray())throw new IllegalArgumentException("Patch '"+id+"' must define an Operations array.");JsonArray array=raw.getAsJsonArray();List<PatchOperation> result=new ArrayList<>();for(int i=0;i<array.size();i++){if(!array.get(i).isJsonObject())throw new IllegalArgumentException("Patch '"+id+"' operation "+i+" must be an object.");result.add(PatchOperation.parse(array.get(i).getAsJsonObject(),id,i,formatVersion));}return result;}
    private static void validateSentinel(List<PatchOperation> operations,String id,int formatVersion){if(!PatchFormat.isVersion2(formatVersion))return;if(operations.isEmpty()||!"RequireFormat".equals(operations.getFirst().op()))throw new IllegalArgumentException("Patch '"+id+"' format 2 requires RequireFormat as operation index zero.");PatchOperation sentinel=operations.getFirst();if(!Integer.valueOf(formatVersion).equals(sentinel.version()))throw new IllegalArgumentException("Patch '"+id+"' RequireFormat version must equal FormatVersion.");for(int i=1;i<operations.size();i++)if("RequireFormat".equals(operations.get(i).op()))throw new IllegalArgumentException("Patch '"+id+"' must not contain a second RequireFormat operation.");}
    private static void validateV2RootFields(JsonObject root){java.util.Set<String> allowed=java.util.Set.of("FormatVersion","Id","Target","Targets","Priority","Enabled","When","Operations");for(String name:root.keySet())if(!allowed.contains(name))throw new IllegalArgumentException("Format 2 patch definition contains unknown root field '"+name+"'.");}
    private static List<String> readTargets(JsonObject root,String id){JsonElement single=root.get("Target"),multiple=root.get("Targets");if(single!=null&&!single.isJsonNull()&&multiple!=null&&!multiple.isJsonNull())throw new IllegalArgumentException("Patch '"+id+"' must define either Target or Targets, not both.");if(multiple==null||multiple.isJsonNull())return List.of(normalize(readRequiredString(root,"Target","Patch '"+id+"'"),id));if(!multiple.isJsonArray())throw new IllegalArgumentException("Patch '"+id+"' Targets must be an array.");if(multiple.getAsJsonArray().isEmpty())throw new IllegalArgumentException("Patch '"+id+"' Targets must not be empty.");Set<String> result=new LinkedHashSet<>();for(int i=0;i<multiple.getAsJsonArray().size();i++){JsonElement target=multiple.getAsJsonArray().get(i);if(!target.isJsonPrimitive()||!target.getAsJsonPrimitive().isString())throw new IllegalArgumentException("Patch '"+id+"' Targets entry "+i+" must be a string.");String normalized=normalize(target.getAsString(),id);if(!result.add(normalized))throw new IllegalArgumentException("Patch '"+id+"' Targets contains duplicate target "+normalized+".");}return List.copyOf(result);}
    private static String normalize(String target,String id){if(target.isBlank())throw new IllegalArgumentException("Patch '"+id+"' target must not be blank.");String normalized=target.replace('\\','/');if(normalized.startsWith("/")||normalized.matches("^[A-Za-z]:.*")||normalized.contains("//"))throw new IllegalArgumentException("Patch '"+id+"' target is unsafe: "+target);for(String segment:normalized.split("/",-1))if(segment.isEmpty()||segment.equals(".")||segment.equals(".."))throw new IllegalArgumentException("Patch '"+id+"' target is unsafe: "+target);return normalized;}
}
